### ISSUE TITLE
`Add Security Key` Error

### ISSUE THREAD

**Issue by navtoj** [ScottPeterJohnson/purelymail-issues#187]
I'm getting the error below after clicking on "Add Security Key".

```Unable to register security key: TypeError. Please try again.```

![image](https://github.com/ScottPeterJohnson/purelymail-issues/assets/20136585/7c867816-6911-4088-a166-b3ec7672568c)

---

The screenshots below are from DevTools.

![image](https://github.com/ScottPeterJohnson/purelymail-issues/assets/20136585/95becdba-3a9b-4234-a214-f70d8a04c64b)

![image](https://github.com/ScottPeterJohnson/purelymail-issues/assets/20136585/53245ca8-2ebf-4789-9e73-a9fe25005f68)

**Comment by ScottPeterJohnson** [comment]
I had to update the webauthn library, but this should now be fixed.

On November 12, 2023 4:31:44 AM PST, Navtoj Chahal ***@***.***> wrote:
>I'm getting the error below after clicking on "Add Security Key".
>
>```Unable to register security key: TypeError. Please try again.```
>
>![image](https://github.com/ScottPeterJohnson/purelymail-issues/assets/20136585/7c867816-6911-4088-a166-b3ec7672568c)
>
>---
>
>The screenshot below is from the DevTools console.
>
><img width="1690" alt="image" src="https://github.com/ScottPeterJohnson/purelymail-issues/assets/20136585/43a2afba-1e4f-4d24-a253-594ad2be5246">
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ScottPeterJohnson/purelymail-issues/issues/187
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ScottPeterJohnson** [comment]
I think it works now from my testing.

**Comment by navtoj** [comment]
Still getting the same error. I've attached a screenshot below of my browser details.

![image](https://github.com/ScottPeterJohnson/purelymail-issues/assets/20136585/e57109f5-6ade-44f3-a5ce-d4469c84bfe7)

**Comment by ScottPeterJohnson** [comment]
Interesting. The specific error from our logs matches this:
https://github.com/bitwarden/clients/issues/6769
I'm guessing some kind of weird Mac-specific recent browser update makes the authenticatorAttachment property _present_ but undefined, instead of not present and undefined, which happens to break some JS. It's monkey-patchable on our end (though I won't be able to test a fix), though maybe the Chrome team will fix it themselves.

**Comment by navtoj** [comment]
Fixed in https://github.com/bitwarden/clients/pull/6799.
